name: Deploy Laravel 11 to AWS Elastic Beanstalk

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, ctype, fileinfo, openssl, tokenizer, xml, gd, pdo_mysql

      - name: Create .env file
        run: |
          cp .env.example .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_ENV=production" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "LOG_CHANNEL=stderr" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          php artisan config:clear

      - name: Set file permissions
        run: |
          # Ensure the directories exist in the application's root
          mkdir -p /var/app/current/storage /var/app/current/bootstrap/cache /var/app/current/public
          sudo chmod -R 775 /var/app/current/storage /var/app/current/bootstrap/cache /var/app/current/public

      - name: Configure Apache for Laravel
        run: |
          mkdir -p .platform/apache2/conf.d
          echo "DocumentRoot /var/app/current/public" > .platform/apache2/conf.d/laravel.conf
          echo "<Directory /var/app/current/public>" >> .platform/apache2/conf.d/laravel.conf
          echo "    Options Indexes FollowSymLinks" >> .platform/apache2/conf.d/laravel.conf
          echo "    AllowOverride All" >> .platform/apache2/conf.d/laravel.conf
          echo "    Require all granted" >> .platform/apache2/conf.d/laravel.conf
          echo "</Directory>" >> .platform/apache2/conf.d/laravel.conf

      - name: Set correct permissions for Elastic Beanstalk directories
        run: |
          # Correct permissions for directories in the deployed app
          sudo chmod -R 775 /var/app/current/storage /var/app/current/bootstrap/cache /var/app/current/public

      - name: Configure Elastic Beanstalk (.ebextensions)
        run: |
          mkdir -p .ebextensions
          echo "container_commands:" > .ebextensions/01-permissions.config
          echo "  01-set-permissions:" >> .ebextensions/01-permissions.config
          echo "    command: 'chmod -R 775 /var/app/current/storage /var/app/current/bootstrap/cache'" >> .ebextensions/01-permissions.config
          echo "    leader_only: false" >> .ebextensions/01-permissions.config

          echo "container_commands:" > .ebextensions/02-migrate.config
          echo "  01-run-migrations:" >> .ebextensions/02-migrate.config
          echo "    command: 'php artisan migrate --force'" >> .ebextensions/02-migrate.config
          echo "    leader_only: true" >> .ebextensions/02-migrate.config

      - name: Package Laravel app
        run: |
          rm -rf node_modules/ .git/ .github/ .env.example
          zip -r ../app.zip . -x "*.git*" "*.env*" "node_modules/*" "tests/*"

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: ${{ secrets.AWS_ELASTICBEANSTALK_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_ELASTICBEANSTALK_ENVIRONMENT_NAME }}
          version_label: "v${{ github.run_number }}-${{ github.sha }}"
          deployment_package: ../app.zip
          wait_for_deployment: true
