name: Deploy Laravel 11 to AWS Elastic Beanstalk

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, ctype, fileinfo, openssl, tokenizer, xml, gd, pdo_mysql

      - name: Create .env file
        run: |
          cp .env.example .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_ENV=production" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "LOG_CHANNEL=stderr" >> .env
          echo "CACHE_DRIVER=array" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_SQLITE_DATABASE=" >> .env  # Disable SQLite

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          php artisan config:clear

      - name: Set file permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Configure Apache
        run: |
          mkdir -p .platform/apache/conf.d
          echo "DocumentRoot /var/app/current/public" > .platform/apache/conf.d/laravel.conf
          echo "<Directory /var/app/current/public>" >> .platform/apache/conf.d/laravel.conf
          echo "    AllowOverride All" >> .platform/apache/conf.d/laravel.conf
          echo "    Require all granted" >> .platform/apache/conf.d/laravel.conf
          echo "</Directory>" >> .platform/apache/conf.d/laravel.conf

      - name: Configure Elastic Beanstalk
        run: |
          mkdir -p .ebextensions
          echo -e "container_commands:\n  01-run-migrations:\n    command: \"php artisan migrate --force\"\n    leader_only: true" > .ebextensions/01-migrations.config
          echo -e "container_commands:\n  01-set-permissions:\n    command: \"chmod -R 775 storage bootstrap/cache\"\n    leader_only: false" > .ebextensions/02-permissions.config

      - name: Package application
        run: |
          rm -rf node_modules/ .git/ .github/ .env.example
          zip -r ../app.zip . -x '*.git*' '*.env*' 'node_modules/*' 'tests/*'

      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: ${{ secrets.AWS_ELASTICBEANSTALK_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_ELASTICBEANSTALK_ENVIRONMENT_NAME }}
          version_label: "v${{ github.run_number }}-${{ github.sha }}"
          deployment_package: ../app.zip
          wait_for_deployment: true
