name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not `main`

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Choose the PHP version you are using
          extensions: mbstring, bcmath, zip
          ini-values: post_max_size=256M, upload_max_filesize=256M

      # Install Composer
      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      # Install dependencies
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      # Set up environment variables
      - name: Set up environment variables
        run: |
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> .env

      # Run tests
      # - name: Run Tests
      #   run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deployment only happens after build and tests pass
    steps:
      # Checkout the code again
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Deploy to AWS Elastic Beanstalk
      - name: Deploy to AWS Elastic Beanstalk
        run: |
          eb init -p php -r ${{ secrets.AWS_DEFAULT_REGION }} --region ${{ secrets.AWS_DEFAULT_REGION }}
          eb use your-environment-name  # Replace with your environment name
          eb deploy

  post-deploy:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      # Send a notification or trigger other actions post-deployment if needed
      - name: Send deployment notification (example)
        run: echo "Deployment to AWS Elastic Beanstalk completed successfully."
