name: Deploy Laravel 11 to AWS Elastic Beanstalk

on:
  push:
    branches: [main] # or 'staging' as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, ctype, fileinfo, openssl, tokenizer, xml, gd, pdo_mysql

      - name: Create .env file for CI
        run: |
          cp .env.example .env
          echo "APP_KEY=base64:$(php -r 'echo base64_encode(random_bytes(32));')" >> .env
          echo "APP_ENV=production" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "LOG_CHANNEL=stderr" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=26130" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan cache:clear

      - name: Set correct permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Create .platform config for Apache
        run: |
          mkdir -p .platform/apache/conf.d
          echo "DocumentRoot /var/app/current/public" > .platform/apache/conf.d/laravel.conf
          echo "<Directory /var/app/current/public>" >> .platform/apache/conf.d/laravel.conf
          echo "    AllowOverride All" >> .platform/apache/conf.d/laravel.conf
          echo "    Require all granted" >> .platform/apache/conf.d/laravel.conf
          echo "</Directory>" >> .platform/apache/conf.d/laravel.conf

      - name: Package Laravel app
        run: |
          rm -rf node_modules/ .git/ .github/
          zip -r ../app.zip . -x '*.git*' '*.env*' -x 'node_modules/*'

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: ${{ secrets.AWS_ELASTICBEANSTALK_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_ELASTICBEANSTALK_ENVIRONMENT_NAME }}
          version_label: "v${{ github.run_number }}-${{ github.sha }}"
          deployment_package: ../app.zip
          wait_for_deployment: true
