name: Deploy Laravel 11 to AWS Elastic Beanstalk

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, ctype, fileinfo, openssl, tokenizer, xml, gd, pdo_mysql

      - name: Create .env file for CI
        run: |
          cp .env.example .env
          echo "APP_KEY=base64:$(php -r 'echo base64_encode(random_bytes(32));')" >> .env
          echo "APP_ENV=production" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "LOG_CHANNEL=stderr" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=26130" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan cache:clear

      - name: Set correct permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Create EB configuration files
        run: |
          mkdir -p .ebextensions

          echo "option_settings:
            aws:elasticbeanstalk:application:environment:
              APP_ENV: production
              APP_DEBUG: false
              LOG_CHANNEL: stderr
              DB_CONNECTION: mysql
              DB_HOST: ${{ secrets.DB_HOST }}
              DB_PORT: 26130
              DB_DATABASE: ${{ secrets.DB_DATABASE }}
              DB_USERNAME: ${{ secrets.DB_USERNAME }}
              DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          " > .ebextensions/01-environment.config

          echo "container_commands:
            01_storage_permissions:
              command: \"chmod -R 775 storage bootstrap/cache\"
              ignoreErrors: false
          " > .ebextensions/02-permissions.config

          echo "container_commands:
            01_migrate:
              command: \"php artisan migrate --force\"
              leader_only: true
            02_optimize:
              command: \"php artisan optimize\"
          " > .ebextensions/03-migrations.config

      - name: Create deployment package
        run: |
          rm -rf node_modules/ .git/ .github/
          zip -r deploy.zip . -x '*.git*' '*.env*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_ELASTICBEANSTALK_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_ELASTICBEANSTALK_ENVIRONMENT_NAME }}
          version_label: "v${{ github.run_number }}"
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
