name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip the web code
        run: |
          zip -r backend.zip .
        
      - name: Upload web zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-zip
          path: backend.zip

      - name: Zip the queue worker code
        run: |
          zip -r backend-queue.zip .
        
      - name: Upload queue worker zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-queue-zip
          path: backend-queue.zip

      - name: Deploy to production web
        uses: atlassian/aws-elasticbeanstalk-deploy@v0.5.2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          APPLICATION_NAME: "stlr-app"
          ENVIRONMENT_NAME: "stlr-app-env"
          ZIP_FILE: "backend.zip"
          S3_BUCKET: "stlr-eb-deployments"
          VERSION_LABEL: "PROJECTNAME__${{ github.sha }}"

  # testing:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Zip the web code
  #       run: |
  #         zip -r backend.zip .
  #       # Upload the zip file as an artifact for the next step
  #     - name: Upload web zip artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: backend-zip
  #         path: backend.zip

  #     - name: Zip the queue worker code
  #       run: |
  #         zip -r backend-queue.zip .
  #       # Upload the zip file as an artifact for the next step
  #     - name: Upload queue worker zip artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: backend-queue-zip
  #         path: backend-queue.zip

  #     - name: Deploy to testing web
  #       uses: atlassian/aws-elasticbeanstalk-deploy@v0.5.2
  #       with:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         AWS_DEFAULT_REGION: "us-east-2"
  #         APPLICATION_NAME: "stlr-app"
  #         ENVIRONMENT_NAME: "test-web"
  #         ZIP_FILE: "backend.zip"
  #         S3_BUCKET: "stlr-eb-deployments"
  #         VERSION_LABEL: "PROJECTNAME__${{ github.sha }}"

  #     - name: Deploy to testing queue server
  #       uses: atlassian/aws-elasticbeanstalk-deploy@v0.5.2
  #       with:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         AWS_DEFAULT_REGION: "us-east-2"
  #         APPLICATION_NAME: "stlr-app"
  #         ENVIRONMENT_NAME: "test-queue"
  #         ZIP_FILE: "backend-queue.zip"
  #         S3_BUCKET: "stlr-eb-deployments"
  #         VERSION_LABEL: "PROJECTNAME--queue__${{ github.sha }}"
